/**
 * Automatically generated by Zserio C++ extension version 2.9.0-pre1.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode, typeInfoCode, reflectionCode, stdAllocator.
 */

#ifndef TEST_OBJECT_STD_ALLOC_CREATOR_ENUM_H
#define TEST_OBJECT_STD_ALLOC_CREATOR_ENUM_H

#include <array>

#include <zserio/Enums.h>
#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/ITypeInfo.h>
#include <zserio/IReflectable.h>
#include <zserio/PackingContext.h>
#include <zserio/ArrayTraits.h>
#include <zserio/Types.h>

namespace test_object
{
namespace std_alloc
{

enum class CreatorEnum : int8_t
{
    ONE = INT8_C(0),
    TWO = INT8_C(1),
    MinusOne = INT8_C(-1)
};

} // namespace std_alloc
} // namespace test_object

namespace zserio
{

// This is full specialization of enumeration traits and methods for CreatorEnum enumeration.
template <>
struct EnumTraits<::test_object::std_alloc::CreatorEnum>
{
    static constexpr ::std::array<const char*, 3> names =
    {{
        "ONE",
        "TWO",
        "MinusOne"
    }};

    static constexpr ::std::array<::test_object::std_alloc::CreatorEnum, 3> values =
    {{
        ::test_object::std_alloc::CreatorEnum::ONE,
        ::test_object::std_alloc::CreatorEnum::TWO,
        ::test_object::std_alloc::CreatorEnum::MinusOne
    }};
};

template <>
const ::zserio::ITypeInfo& enumTypeInfo<::test_object::std_alloc::CreatorEnum, ::std::allocator<uint8_t>>();

template <>
::zserio::IReflectablePtr enumReflectable(::test_object::std_alloc::CreatorEnum value, const ::std::allocator<uint8_t>& allocator);

template <>
size_t enumToOrdinal<::test_object::std_alloc::CreatorEnum>(::test_object::std_alloc::CreatorEnum value);

template <>
::test_object::std_alloc::CreatorEnum valueToEnum<::test_object::std_alloc::CreatorEnum>(
        typename ::std::underlying_type<::test_object::std_alloc::CreatorEnum>::type rawValue);

template <>
uint32_t enumHashCode<::test_object::std_alloc::CreatorEnum>(::test_object::std_alloc::CreatorEnum value);

template <>
void initPackingContext<::zserio::PackingContextNode, ::test_object::std_alloc::CreatorEnum>(
        ::zserio::PackingContextNode& contextNode, ::test_object::std_alloc::CreatorEnum value);

template <>
size_t bitSizeOf<::test_object::std_alloc::CreatorEnum>(::test_object::std_alloc::CreatorEnum value);

template <>
size_t bitSizeOf<::zserio::PackingContextNode, ::test_object::std_alloc::CreatorEnum>(
        ::zserio::PackingContextNode& contextNode, ::test_object::std_alloc::CreatorEnum value);

template <>
size_t initializeOffsets<::test_object::std_alloc::CreatorEnum>(size_t bitPosition, ::test_object::std_alloc::CreatorEnum value);

template <>
size_t initializeOffsets<::zserio::PackingContextNode, ::test_object::std_alloc::CreatorEnum>(
        ::zserio::PackingContextNode& contextNode, size_t bitPosition, ::test_object::std_alloc::CreatorEnum value);

template <>
::test_object::std_alloc::CreatorEnum read<::test_object::std_alloc::CreatorEnum>(::zserio::BitStreamReader& in);

template <>
::test_object::std_alloc::CreatorEnum read<::test_object::std_alloc::CreatorEnum, ::zserio::PackingContextNode>(
        ::zserio::PackingContextNode& contextNode, ::zserio::BitStreamReader& in);

template <>
void write<::test_object::std_alloc::CreatorEnum>(::zserio::BitStreamWriter& out, ::test_object::std_alloc::CreatorEnum value);

template <>
void write<::zserio::PackingContextNode, ::test_object::std_alloc::CreatorEnum>(
        ::zserio::PackingContextNode& contextNode, ::zserio::BitStreamWriter& out, ::test_object::std_alloc::CreatorEnum value);

} // namespace zserio

#endif // TEST_OBJECT_STD_ALLOC_CREATOR_ENUM_H
