<#macro file_header generatorDescription>
/**
 * Automatically generated by ${generatorDescription}.
 */
</#macro>

<#macro package packageName>
    <#if packageName?? && packageName != "">
package ${packageName};
    </#if>
</#macro>

<#macro imports importsList>
    <#list importsList as importSpec>
import ${importSpec};
    </#list>
</#macro>

<#macro standard_header generatorDescription packageName importsList>
<@file_header generatorDescription/>

<@package packageName/>

<@imports importsList/>
</#macro>
