// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: zserio_service.proto
#ifndef GRPC_zserio_5fservice_2eproto__INCLUDED
#define GRPC_zserio_5fservice_2eproto__INCLUDED

#include "zserio_service.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace zserio_service_grpc {

class ZserioService final {
 public:
  static constexpr char const* service_full_name() {
    return "zserio_service_grpc.ZserioService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status callProcedure(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::zserio_service_grpc::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zserio_service_grpc::Response>> AsynccallProcedure(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zserio_service_grpc::Response>>(AsynccallProcedureRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zserio_service_grpc::Response>> PrepareAsynccallProcedure(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::zserio_service_grpc::Response>>(PrepareAsynccallProcedureRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::zserio_service_grpc::Response>* AsynccallProcedureRaw(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::zserio_service_grpc::Response>* PrepareAsynccallProcedureRaw(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status callProcedure(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::zserio_service_grpc::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zserio_service_grpc::Response>> AsynccallProcedure(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zserio_service_grpc::Response>>(AsynccallProcedureRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zserio_service_grpc::Response>> PrepareAsynccallProcedure(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::zserio_service_grpc::Response>>(PrepareAsynccallProcedureRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::zserio_service_grpc::Response>* AsynccallProcedureRaw(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::zserio_service_grpc::Response>* PrepareAsynccallProcedureRaw(::grpc::ClientContext* context, const ::zserio_service_grpc::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_callProcedure_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status callProcedure(::grpc::ServerContext* context, const ::zserio_service_grpc::Request* request, ::zserio_service_grpc::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_callProcedure : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_callProcedure() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_callProcedure() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callProcedure(::grpc::ServerContext* context, const ::zserio_service_grpc::Request* request, ::zserio_service_grpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcallProcedure(::grpc::ServerContext* context, ::zserio_service_grpc::Request* request, ::grpc::ServerAsyncResponseWriter< ::zserio_service_grpc::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_callProcedure<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_callProcedure : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_callProcedure() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_callProcedure() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callProcedure(::grpc::ServerContext* context, const ::zserio_service_grpc::Request* request, ::zserio_service_grpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_callProcedure : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_callProcedure() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_callProcedure() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status callProcedure(::grpc::ServerContext* context, const ::zserio_service_grpc::Request* request, ::zserio_service_grpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcallProcedure(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_callProcedure : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_callProcedure() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::zserio_service_grpc::Request, ::zserio_service_grpc::Response>(std::bind(&WithStreamedUnaryMethod_callProcedure<BaseClass>::StreamedcallProcedure, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_callProcedure() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status callProcedure(::grpc::ServerContext* context, const ::zserio_service_grpc::Request* request, ::zserio_service_grpc::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcallProcedure(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::zserio_service_grpc::Request,::zserio_service_grpc::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_callProcedure<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_callProcedure<Service > StreamedService;
};

}  // namespace zserio_service_grpc


#endif  // GRPC_zserio_5fservice_2eproto__INCLUDED
