/**
 * Automatically generated by Zserio C++ extension version 1.2.0.
 */

#ifndef MAP_CONCRETE_MAP_H
#define MAP_CONCRETE_MAP_H


#include <map/Map.h>
#include <map/ConcreteType.h>
#include <map/ConcreteValue.h>

namespace map
{

typedef ::map::Map<::map::ConcreteType, ::map::ConcreteValue> ConcreteMap;

} // namespace map

#endif // MAP_CONCRETE_MAP_H
