package array_types_warning;

import array_types_warning.packed_array_choice_has_no_packable_field.*;
import array_types_warning.packed_array_struct_has_no_packable_field.*;
import array_types_warning.packed_array_template_has_no_packable_field.*;
import array_types_warning.packed_array_unpackable_bool_element.*;
import array_types_warning.packed_array_unpackable_extern_element.*;
import array_types_warning.packed_array_unpackable_bytes_element.*;
import array_types_warning.packed_array_unpackable_float_element.*;
import array_types_warning.packed_array_unpackable_string_element.*;
import array_types_warning.packed_array_union_has_no_packable_field.*;
