package zserio.ast;

import java.util.List;
import java.util.ArrayList;
import zserio.antlr.ZserioParserTokenTypes;
import zserio.antlr.util.BaseTokenAST;
import zserio.antlr.util.ParserException;

/**
 * AST node for service types.
 *
 * Service types are Zserio types as well.
 */
public class ServiceType extends TokenAST implements ZserioType
{
    public ServiceType()
    {
        ZserioTypeContainer.add(this);
    }

    @Override
    public Package getPackage()
    {
        return pkg;
    }

    @Override
    public String getName()
    {
        return name;
    }

    @Override
    public Iterable<ZserioType> getUsedTypeList()
    {
        throw new InternalError("ServiceType.getUsedTypeList() is not implemented!");
    }

    @Override
    public void callVisitor(ZserioTypeVisitor visitor)
    {
        visitor.visitServiceType(this);
    }

    /**
     * Gets the scope defined by this type.
     *
     * @return The scope defined by this type.
     */
    public Scope getScope()
    {
        return scope;
    }

    /**
     * Sets lexical scope and package for the enumeration type.
     *
     * This method is called by code generated by ANTLR using TypeEvaluator.g.
     *
     * @param scope Lexical scope to set.
     * @param pkg   Package to set.
     */
    public void setScope(Scope scope, Package pkg)
    {
        this.scope = scope;
        this.pkg = pkg;
    }

    public Iterable<Rpc> getRpcList()
    {
            return rpcs;
    }

    @Override
    protected boolean evaluateChild(BaseTokenAST child) throws ParserException
    {
        switch (child.getType())
        {
        case ZserioParserTokenTypes.ID:
            if (!(child instanceof IdToken))
                return false;
            name = child.getText();
            break;

        case ZserioParserTokenTypes.RPC:
            if (!(child instanceof Rpc))
                return false;
            final Rpc rpc = (Rpc)child;
            rpc.setServiceType(this);
            rpcs.add(rpc);
            break;

        default:
            return false;
        }

        return true;
    }

    @Override
    protected void evaluate() throws ParserException
    {
        evaluateHiddenDocComment(this);
    }

    private static final long serialVersionUID = -6520580190710341443L;


    private Scope scope;
    private Package pkg;

    private String name;
    private List<Rpc> rpcs = new ArrayList<Rpc>();
}
