// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zserio_service.proto

package zserio_service_grpc;

public final class ZserioServiceProto {
  private ZserioServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zserio_service_grpc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string procName = 1;</code>
     */
    java.lang.String getProcName();
    /**
     * <code>string procName = 1;</code>
     */
    com.google.protobuf.ByteString
        getProcNameBytes();

    /**
     * <code>bytes requestData = 2;</code>
     */
    com.google.protobuf.ByteString getRequestData();
  }
  /**
   * Protobuf type {@code zserio_service_grpc.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zserio_service_grpc.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      procName_ = "";
      requestData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              procName_ = s;
              break;
            }
            case 18: {

              requestData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zserio_service_grpc.ZserioServiceProto.Request.class, zserio_service_grpc.ZserioServiceProto.Request.Builder.class);
    }

    public static final int PROCNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object procName_;
    /**
     * <code>string procName = 1;</code>
     */
    public java.lang.String getProcName() {
      java.lang.Object ref = procName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        procName_ = s;
        return s;
      }
    }
    /**
     * <code>string procName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProcNameBytes() {
      java.lang.Object ref = procName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        procName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString requestData_;
    /**
     * <code>bytes requestData = 2;</code>
     */
    public com.google.protobuf.ByteString getRequestData() {
      return requestData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProcNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, procName_);
      }
      if (!requestData_.isEmpty()) {
        output.writeBytes(2, requestData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProcNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, procName_);
      }
      if (!requestData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, requestData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zserio_service_grpc.ZserioServiceProto.Request)) {
        return super.equals(obj);
      }
      zserio_service_grpc.ZserioServiceProto.Request other = (zserio_service_grpc.ZserioServiceProto.Request) obj;

      boolean result = true;
      result = result && getProcName()
          .equals(other.getProcName());
      result = result && getRequestData()
          .equals(other.getRequestData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROCNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProcName().hashCode();
      hash = (37 * hash) + REQUESTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRequestData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zserio_service_grpc.ZserioServiceProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zserio_service_grpc.ZserioServiceProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zserio_service_grpc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zserio_service_grpc.Request)
        zserio_service_grpc.ZserioServiceProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zserio_service_grpc.ZserioServiceProto.Request.class, zserio_service_grpc.ZserioServiceProto.Request.Builder.class);
      }

      // Construct using zserio_service_grpc.ZserioServiceProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        procName_ = "";

        requestData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Request_descriptor;
      }

      public zserio_service_grpc.ZserioServiceProto.Request getDefaultInstanceForType() {
        return zserio_service_grpc.ZserioServiceProto.Request.getDefaultInstance();
      }

      public zserio_service_grpc.ZserioServiceProto.Request build() {
        zserio_service_grpc.ZserioServiceProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zserio_service_grpc.ZserioServiceProto.Request buildPartial() {
        zserio_service_grpc.ZserioServiceProto.Request result = new zserio_service_grpc.ZserioServiceProto.Request(this);
        result.procName_ = procName_;
        result.requestData_ = requestData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zserio_service_grpc.ZserioServiceProto.Request) {
          return mergeFrom((zserio_service_grpc.ZserioServiceProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zserio_service_grpc.ZserioServiceProto.Request other) {
        if (other == zserio_service_grpc.ZserioServiceProto.Request.getDefaultInstance()) return this;
        if (!other.getProcName().isEmpty()) {
          procName_ = other.procName_;
          onChanged();
        }
        if (other.getRequestData() != com.google.protobuf.ByteString.EMPTY) {
          setRequestData(other.getRequestData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zserio_service_grpc.ZserioServiceProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zserio_service_grpc.ZserioServiceProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object procName_ = "";
      /**
       * <code>string procName = 1;</code>
       */
      public java.lang.String getProcName() {
        java.lang.Object ref = procName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          procName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string procName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProcNameBytes() {
        java.lang.Object ref = procName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          procName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string procName = 1;</code>
       */
      public Builder setProcName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        procName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string procName = 1;</code>
       */
      public Builder clearProcName() {
        
        procName_ = getDefaultInstance().getProcName();
        onChanged();
        return this;
      }
      /**
       * <code>string procName = 1;</code>
       */
      public Builder setProcNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        procName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes requestData = 2;</code>
       */
      public com.google.protobuf.ByteString getRequestData() {
        return requestData_;
      }
      /**
       * <code>bytes requestData = 2;</code>
       */
      public Builder setRequestData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes requestData = 2;</code>
       */
      public Builder clearRequestData() {
        
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zserio_service_grpc.Request)
    }

    // @@protoc_insertion_point(class_scope:zserio_service_grpc.Request)
    private static final zserio_service_grpc.ZserioServiceProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zserio_service_grpc.ZserioServiceProto.Request();
    }

    public static zserio_service_grpc.ZserioServiceProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public zserio_service_grpc.ZserioServiceProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zserio_service_grpc.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes responseData = 1;</code>
     */
    com.google.protobuf.ByteString getResponseData();
  }
  /**
   * Protobuf type {@code zserio_service_grpc.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zserio_service_grpc.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      responseData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              responseData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zserio_service_grpc.ZserioServiceProto.Response.class, zserio_service_grpc.ZserioServiceProto.Response.Builder.class);
    }

    public static final int RESPONSEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString responseData_;
    /**
     * <code>bytes responseData = 1;</code>
     */
    public com.google.protobuf.ByteString getResponseData() {
      return responseData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!responseData_.isEmpty()) {
        output.writeBytes(1, responseData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!responseData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, responseData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof zserio_service_grpc.ZserioServiceProto.Response)) {
        return super.equals(obj);
      }
      zserio_service_grpc.ZserioServiceProto.Response other = (zserio_service_grpc.ZserioServiceProto.Response) obj;

      boolean result = true;
      result = result && getResponseData()
          .equals(other.getResponseData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getResponseData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static zserio_service_grpc.ZserioServiceProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zserio_service_grpc.ZserioServiceProto.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zserio_service_grpc.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zserio_service_grpc.Response)
        zserio_service_grpc.ZserioServiceProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zserio_service_grpc.ZserioServiceProto.Response.class, zserio_service_grpc.ZserioServiceProto.Response.Builder.class);
      }

      // Construct using zserio_service_grpc.ZserioServiceProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zserio_service_grpc.ZserioServiceProto.internal_static_zserio_service_grpc_Response_descriptor;
      }

      public zserio_service_grpc.ZserioServiceProto.Response getDefaultInstanceForType() {
        return zserio_service_grpc.ZserioServiceProto.Response.getDefaultInstance();
      }

      public zserio_service_grpc.ZserioServiceProto.Response build() {
        zserio_service_grpc.ZserioServiceProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zserio_service_grpc.ZserioServiceProto.Response buildPartial() {
        zserio_service_grpc.ZserioServiceProto.Response result = new zserio_service_grpc.ZserioServiceProto.Response(this);
        result.responseData_ = responseData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zserio_service_grpc.ZserioServiceProto.Response) {
          return mergeFrom((zserio_service_grpc.ZserioServiceProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zserio_service_grpc.ZserioServiceProto.Response other) {
        if (other == zserio_service_grpc.ZserioServiceProto.Response.getDefaultInstance()) return this;
        if (other.getResponseData() != com.google.protobuf.ByteString.EMPTY) {
          setResponseData(other.getResponseData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zserio_service_grpc.ZserioServiceProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zserio_service_grpc.ZserioServiceProto.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes responseData = 1;</code>
       */
      public com.google.protobuf.ByteString getResponseData() {
        return responseData_;
      }
      /**
       * <code>bytes responseData = 1;</code>
       */
      public Builder setResponseData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes responseData = 1;</code>
       */
      public Builder clearResponseData() {
        
        responseData_ = getDefaultInstance().getResponseData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zserio_service_grpc.Response)
    }

    // @@protoc_insertion_point(class_scope:zserio_service_grpc.Response)
    private static final zserio_service_grpc.ZserioServiceProto.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zserio_service_grpc.ZserioServiceProto.Response();
    }

    public static zserio_service_grpc.ZserioServiceProto.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public zserio_service_grpc.ZserioServiceProto.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zserio_service_grpc_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zserio_service_grpc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zserio_service_grpc_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zserio_service_grpc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024zserio_service.proto\022\023zserio_service_g" +
      "rpc\"0\n\007Request\022\020\n\010procName\030\001 \001(\t\022\023\n\013requ" +
      "estData\030\002 \001(\014\" \n\010Response\022\024\n\014responseDat" +
      "a\030\001 \001(\0142_\n\rZserioService\022N\n\rcallProcedur" +
      "e\022\034.zserio_service_grpc.Request\032\035.zserio" +
      "_service_grpc.Response\"\000B\024B\022ZserioServic" +
      "eProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_zserio_service_grpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zserio_service_grpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zserio_service_grpc_Request_descriptor,
        new java.lang.String[] { "ProcName", "RequestData", });
    internal_static_zserio_service_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zserio_service_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zserio_service_grpc_Response_descriptor,
        new java.lang.String[] { "ResponseData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
