# set gcc
set(CMAKE_C_COMPILER gcc$ENV{GCC_VERSION_SUFFIX})
set(CMAKE_CXX_COMPILER g++$ENV{GCC_VERSION_SUFFIX})

# set -m64
set(COMPILER_M64_FLAG "-m64")

# set C flags
set(CMAKE_C_FLAGS_INIT "${COMPILER_M64_FLAG}")

# set CXX flags
set(CMAKE_CXX_FLAGS_INIT "${COMPILER_M64_FLAG}")
