name: Windows Doc

on:
  workflow_call:

jobs:
  doc:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: "windows-2022" }

    runs-on: ${{matrix.os}}
    name: ${{matrix.os}}

    steps:
    - name: "Set up environment"
      shell: bash
      run: |
        echo "NU_HTML_VALIDATOR=${RUNNER_WORKSPACE}/vnu-20.6.30/vnu.jar" >> ${GITHUB_ENV}

    - name: Install dependencies
      shell: bash
      run: |
        choco install graphviz
        choco install wget
        choco install zip

    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "8"

    - name: Install specific version of HTML validator (v.Nu)
      shell: bash
      run: |
        wget -P "${RUNNER_WORKSPACE}" \
            https://github.com/validator/validator/releases/download/20.6.30/vnu.jar_20.6.30.zip
        unzip "${RUNNER_WORKSPACE}\vnu.jar_20.6.30.zip" -d "${RUNNER_WORKSPACE}"
        mv "${RUNNER_WORKSPACE}\dist" "${RUNNER_WORKSPACE}\vnu-20.6.30"

    - name: "Convert environment variables to POSIX paths"
      shell: bash
      run: |
        echo "ANT=/${ANT_HOME}/bin/ant" | sed -e 's/\\/\//g' -e 's/://' >> ${GITHUB_ENV}
        echo "JAVA_HOME=/${JAVA_HOME}" | sed -e 's/\\/\//g' -e 's/://' >> ${GITHUB_ENV}
        echo "NU_HTML_VALIDATOR=/${NU_HTML_VALIDATOR}" | sed -e 's/\\/\//g' -e 's/://' >> ${GITHUB_ENV}

    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download Zserio release artifact
      uses: actions/download-artifact@v4
      with:
        name: zserio-bin-java8

    - name: Run Zserio tests
      shell: bash
      run: |
        scripts/test.sh doc

    - name: Run Zserio tests with extra arguments
      shell: bash
      run: |
        export ZSERIO_EXTRA_ARGS="-withTypeInfoCode -withCodeComments"
        scripts/test.sh -p -i arguments/without_writer_code doc

        export ZSERIO_EXTRA_ARGS="${ZSERIO_EXTRA_ARGS} -withValidationCode -withRangeCheckCode"
        scripts/test.sh -p -x arguments/without_writer_code doc

    - name: Run Zserio integration tests for repeated generation
      shell: bash
      run: |
        scripts/test_gen.sh doc
